site_name: 红红的小怪物-学习笔记
site_description: java开发工程学习历程
site_author: 红红的小怪物
site_url: https://zxbmmt.github.io/study-notes/

repo_name: 'ZXBmmt/study-notes'
repo_url: 'https://github.com/ZXBmmt/study-notes'


theme:
  name: material
  features:
    - navigation.tabs
  palette:
    scheme: default
    primary: indigo
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  favicon: assets/favicon.png
  icon:
    logo: logo
  language: 'zh'

# extra:
#   social:
#     - type: github
#       link: https://github.com/ZXBmmt
#   search:
#     language: 'jp'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

extra_javascript:
  - 'js/extra.js'
  - 'js/baidu-tongji.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

nav:
  # - 介绍:
  - 计算机基础:
      - 1. 计算机网络: computer-basics/network.md
      - 2. 操作系统: computer-basics/operating-system.md
  - Java基础:
      - 1. 集合: java/collection.md
      - 2. io: java/io.md
      - 3. 并发: java/concurrent.md
      - 4. JMM: java/jmm.md
      - 5. JVM: java/jvm.md
      - 6. 垃圾回收: java/gc.md
  - MySql: index.md
  - Redis: index.md
  - Spring: index.md
  - MyBatis: index.md
  - SpringMVC: index.md
  - SpringBoot: index.md
  - Spring Cloud: index.md
  - MQ: index.md
  - ELK: index.md
  - 监控: index.md
  - Docker: index.md
  - K8S: index.md
  - Hadoop: index.md

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
