site_name: 红红的小怪物-学习笔记
theme:
  name: material


nav:
  - 介绍: index.md
  - Java基础: index.md
  - 操作系统: index.md
  - MySql: index.md
  - Redis: index.md
  - Spring: index.md
  - MyBatis: index.md
  - SpringMVC: index.md
  - SpringBoot: index.md
  - Spring Cloud: index.md
  - MQ: index.md
  - ELK: index.md
  - Hadoop: index.md


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
